# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_cpp <- function(brts, init_pars, sample_size, maxN, plugin, soc, max_misssing, max_lambda, lower_bound, upper_bound, xtol, num_threads, copy_trees) {
    .Call(`_remphasis_rcpp_mcem`, brts, init_pars, sample_size, maxN, plugin, soc, max_misssing, max_lambda, lower_bound, upper_bound, xtol, num_threads, copy_trees)
}

