# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcem <- function(brts_i, init_pars_i, sample_size, plugin, soc = 2L, max_misssing = 10000L, max_lambda = 500.0, lower_bound_i = numeric(), upper_bound_i = numeric(), xtol = 0.001, num_threads = 0L, copy_trees = FALSE, verbose = TRUE) {
    .Call(`_remphasis_rcpp_mcem`, brts_i, init_pars_i, sample_size, plugin, soc, max_misssing, max_lambda, lower_bound_i, upper_bound_i, xtol, num_threads, copy_trees, verbose)
}

