# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_cpp <- function(brts_i, init_pars_i, sample_size, plugin, soc, cont, max_misssing, max_lambda, lower_bound_i, upper_bound_i, xtol, num_threads, copy_trees, verbose) {
    .Call(`_remphasis_rcpp_mcem`, brts_i, init_pars_i, sample_size, plugin, soc, cont, max_misssing, max_lambda, lower_bound_i, upper_bound_i, xtol, num_threads, copy_trees, verbose)
}

